"""add provider_id and metadata to payments

Revision ID: 0697d8992d4d
Revises: 81842fb87d25
Create Date: 2026-05-10 20:17:46.983003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0697d8992d4d'
down_revision: Union[str, Sequence[str], None] = '81842fb87d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('provider_id', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'metadata')
    op.drop_column('payments', 'provider_id')
    # ### end Alembic commands ###
