"""init

Revision ID: 38c2e1e12657
Revises:
Create Date: 2026-06-07 23:32:12.114852

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "38c2e1e12657"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "PENDING",
                "PROCESSING",
                "SUCCESS",
                "ERROR",
                "FAILED",
                name="payment_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "failure_reason",
            sa.Enum(
                "TIMEOUT", "INSUFFICIENT_FUNDS", "FRAUD", "LIMIT_EXCEEDED", name="failurereasons"
            ),
            nullable=True,
        ),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payments")
    # PostgreSQL keeps standalone enum types after DROP TABLE; remove them so
    # a fresh upgrade can create the types again after a downgrade to base.
    sa.Enum(name="payment_status").drop(op.get_bind())
    sa.Enum(name="failurereasons").drop(op.get_bind())
    # ### end Alembic commands ###
